In [ ]:
# Data Source:
# https://www.citibikenyc.com/system-data
# https://s3.amazonaws.com/tripdata/index.html

In [1]:
import os
import pandas as pd
import numpy as np
import pickle
from collections import Counter

In [2]:
PATH = "./NYC-bike-share/2017/"
for dirpath, dirs, files in os.walk(PATH):
    print('load files')

load files

In [3]:
csv_files = [i for i in files if i.endswith('csv')]
# csv_files = csv_files[::-1]
csv_files

['201701-citibike-tripdata.csv',
 '201702-citibike-tripdata.csv',
 '201703-citibike-tripdata.csv',
 '201704-citibike-tripdata.csv',
 '201705-citibike-tripdata.csv',
 '201706-citibike-tripdata.csv',
 '201707-citibike-tripdata.csv',
 '201708-citibike-tripdata.csv',
 '201709-citibike-tripdata.csv',
 '201710-citibike-tripdata.csv',
 '201711-citibike-tripdata.csv',
 '201712-citibike-tripdata.csv',
 'JC-201701-citibike-tripdata.csv',
 'JC-201702-citibike-tripdata.csv',
 'JC-201703-citibike-tripdata.csv',
 'JC-201704-citibike-tripdata.csv',
 'JC-201705-citibike-tripdata.csv',
 'JC-201706-citibike-tripdata.csv',
 'JC-201707-citibike-tripdata.csv',
 'JC-201708 citibike-tripdata.csv',
 'JC-201709-citibike-tripdata.csv',
 'JC-201710-citibike-tripdata.csv',
 'JC-201711-citibike-tripdata.csv',
 'JC-201712-citibike-tripdata.csv']

In [4]:
%%time
""" read all csv, concat them and remove necessary rows
"""
df = pd.DataFrame()
list_ = []
for f in csv_files:
    if '2017' in f:
        df_tmp = pd.read_csv('./NYC-bike-share/2017/' + f, index_col=None, header=None, low_memory=False)
        list_.append(df_tmp)
df = pd.concat(list_)

CPU times: user 1min 5s, sys: 13.9 s, total: 1min 19s
Wall time: 1min 20s

In [5]:
df.columns = ['tripduration', 'starttime', 'stoptime', 'start station id',
       'start station name', 'start station latitude',
       'start station longitude', 'end station id', 'end station name',
       'end station latitude', 'end station longitude', 'bikeid', 'usertype',
       'birth year', 'gender']

In [6]:
%%time
df = df.reset_index()

CPU times: user 7.89 s, sys: 9.6 s, total: 17.5 s
Wall time: 18.7 s

In [7]:
%%time
idx = df[(df['tripduration'] == 'tripduration') | (df['tripduration'] == 'Trip Duration')].index
df.drop(idx, 0, inplace=True)

CPU times: user 6.62 s, sys: 1.36 s, total: 7.99 s
Wall time: 8.23 s

In [8]:
df.shape

(16659584, 16)

In [9]:
df.head()

,index,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,1282,2017-01-01 00:00:45,2017-01-01 00:22:08,3263,Cooper Square & E 7 St,40.7292,-73.9909,498,Broadway & W 32 St,40.7485,-73.9881,21136,Subscriber,1987,2
1,1,648,2017-01-01 00:00:57,2017-01-01 00:11:46,3143,5 Ave & E 78 St,40.7768,-73.9639,3152,3 Ave & E 71 St,40.7687,-73.9612,18147,Customer,NaN,0
2,2,631,2017-01-01 00:01:10,2017-01-01 00:11:42,3143,5 Ave & E 78 St,40.7768,-73.9639,3152,3 Ave & E 71 St,40.7687,-73.9612,21211,Customer,NaN,0
3,3,621,2017-01-01 00:01:25,2017-01-01 00:11:47,3143,5 Ave & E 78 St,40.7768,-73.9639,3152,3 Ave & E 71 St,40.7687,-73.9612,26819,Customer,NaN,0
4,4,666,2017-01-01 00:01:51,2017-01-01 00:12:57,3163,Central Park West & W 68 St,40.7734,-73.9778,3163,Central Park West & W 68 St,40.7734,-73.9778,16050,Subscriber,2000,1

In [10]:
df[df['end station id']==3215].head(1)

Empty DataFrame
Columns: [index, tripduration, starttime, stoptime, start station id, start station name, start station latitude, start station longitude, end station id, end station name, end station latitude, end station longitude, bikeid, usertype, birth year, gender]
Index: []

In [13]:
df[df['end station id']==3478]

,index,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
7751770,935517,2048,2017-07-18 14:52:36,2017-07-18 15:26:45,3432,NYCBS Depot - GOW,40.6691,-73.9946,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,27445,Subscriber,1988,2
7756357,940104,876,2017-07-18 16:21:54,2017-07-18 16:36:31,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,21434,Subscriber,1991,2
7774487,958234,131,2017-07-18 19:12:25,2017-07-18 19:14:36,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,21266,Subscriber,1986,2
7788309,972056,1049,2017-07-19 01:38:40,2017-07-19 01:56:10,3409,Bergen St & Smith St,40.6867,-73.9906,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,16312,Subscriber,1977,1
7790170,973917,1690,2017-07-19 06:38:56,2017-07-19 07:07:06,344,Monroe St & Bedford Ave,40.6851,-73.9538,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,25362,Customer,NaN,0
7791558,975305,1410,2017-07-19 07:11:14,2017-07-19 07:34:45,3413,Wyckoff St & 3 Ave,40.6828,-73.9826,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,27021,Subscriber,1967,2
7793068,976815,1758,2017-07-19 07:38:18,2017-07-19 08:07:36,361,Allen St & Hester St,40.7161,-73.9919,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,30001,Subscriber,1987,1
7794846,978593,1313,2017-07-19 08:00:40,2017-07-19 08:22:33,244,Willoughby Ave & Hall St,40.692,-73.9654,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,21550,Subscriber,1993,1
7794944,978691,1126,2017-07-19 08:01:47,2017-07-19 08:20:33,3414,Bergen St & Flatbush Ave,40.6809,-73.9757,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,20950,Subscriber,1987,1
7795436,979183,1048,2017-07-19 08:07:37,2017-07-19 08:25:05,3423,West Drive & Prospect Park West,40.6611,-73.9795,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,26073,Subscriber,1980,2
7795763,979510,1999,2017-07-19 08:11:09,2017-07-19 08:44:28,412,Forsyth St & Canal St,40.7158,-73.9942,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,27476,Subscriber,1988,2
7798910,982657,595,2017-07-19 08:42:06,2017-07-19 08:52:01,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,25352,Subscriber,1988,1
7802627,986374,945,2017-07-19 09:21:12,2017-07-19 09:36:58,3419,Douglass St & 4 Ave,40.6793,-73.9815,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,26852,Subscriber,1990,1
7805800,989547,463,2017-07-19 10:13:24,2017-07-19 10:21:08,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,29342,Subscriber,1981,1
7811225,994972,1346,2017-07-19 12:34:55,2017-07-19 12:57:22,353,S Portland Ave & Hanson Pl,40.6854,-73.9743,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,28908,Customer,1984,1
7814912,998659,83,2017-07-19 13:58:06,2017-07-19 13:59:30,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,27476,Subscriber,1990,1
7823915,1007662,2120,2017-07-19 16:56:08,2017-07-19 17:31:28,330,Reade St & Broadway,40.7145,-74.0056,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,29322,Subscriber,1986,1
7825985,1009732,1267,2017-07-19 17:18:01,2017-07-19 17:39:09,3349,Grand Army Plaza & Plaza St West,40.673,-73.9709,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,25955,Subscriber,1987,2
7835168,1018915,2404,2017-07-19 18:36:25,2017-07-19 19:16:29,304,Broadway & Battery Pl,40.7046,-74.0136,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,21372,Subscriber,1980,1
7836631,1020378,712,2017-07-19 18:49:20,2017-07-19 19:01:13,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,26576,Customer,1992,1
7836662,1020409,694,2017-07-19 18:49:41,2017-07-19 19:01:15,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,15593,Subscriber,1989,1
7837827,1021574,1606,2017-07-19 19:01:37,2017-07-19 19:28:24,3311,Columbia St & Kane St,40.6876,-74.0016,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,30047,Subscriber,1954,1
7839149,1022896,399,2017-07-19 19:15:59,2017-07-19 19:22:38,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,17349,Subscriber,1987,0
7841955,1025702,1615,2017-07-19 19:51:26,2017-07-19 20:18:21,3477,39 St & 2 Ave - Citi Bike HQ at Industry City,40.6554,-74.0106,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,18032,Subscriber,1989,1
7854980,1038727,566,2017-07-20 07:00:55,2017-07-20 07:10:21,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,29890,Subscriber,1989,1
7855061,1038808,2095,2017-07-20 07:02:57,2017-07-20 07:37:52,3041,Kingston Ave & Herkimer St,40.6789,-73.9414,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,29061,Subscriber,1987,1
7858582,1042329,1186,2017-07-20 08:00:59,2017-07-20 08:20:46,3414,Bergen St & Flatbush Ave,40.6809,-73.9757,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,29814,Subscriber,1987,1
7862718,1046465,3025,2017-07-20 08:44:32,2017-07-20 09:34:58,539,Metropolitan Ave & Bedford Ave,40.7153,-73.9602,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,24919,Subscriber,1993,2
7862937,1046684,1175,2017-07-20 08:46:39,2017-07-20 09:06:15,3416,7 Ave & Park Pl,40.6776,-73.9732,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,26673,Subscriber,1993,1
7863346,1047093,712,2017-07-20 08:50:20,2017-07-20 09:02:13,3403,4 Ave & 9 St,40.6705,-73.9888,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,25569,Subscriber,1982,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12176256,1807906,82,2017-09-29 17:27:38,2017-09-29 17:29:00,3477,39 St & 2 Ave - Citi Bike HQ at Industry City,40.6554,-74.0106,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,18425,Subscriber,1995,1
12184969,1816619,1647,2017-09-29 18:51:16,2017-09-29 19:18:44,324,DeKalb Ave & Hudson Ave,40.6899,-73.981,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,15900,Subscriber,1983,1
12186225,1817875,1058,2017-09-29 19:07:01,2017-09-29 19:24:39,3417,Baltic St & 5 Ave,40.6796,-73.9785,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,16340,Customer,1986,1
12188785,1820435,1294,2017-09-29 19:44:55,2017-09-29 20:06:30,3358,Garfield Pl & 8 Ave,40.6712,-73.9748,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,15388,Subscriber,1959,1
12190953,1822603,1922,2017-09-29 20:30:21,2017-09-29 21:02:24,436,Hancock St & Bedford Ave,40.6822,-73.954,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,28887,Subscriber,1986,1
12192086,1823736,1340,2017-09-29 21:02:24,2017-09-29 21:24:44,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,24914,Customer,NaN,0
12192402,1824052,619,2017-09-29 21:11:48,2017-09-29 21:22:08,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,31402,Subscriber,1969,0
12198268,1829918,610,2017-09-30 04:30:05,2017-09-30 04:40:16,3310,14 St & 7 Ave,40.6638,-73.984,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,30922,Subscriber,1987,2
12198985,1830635,952,2017-09-30 07:22:10,2017-09-30 07:38:02,3368,5 Ave & 3 St,40.6728,-73.9835,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,25496,Subscriber,1956,1
12199258,1830908,1486,2017-09-30 07:42:37,2017-09-30 08:07:23,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,28887,Subscriber,1956,1
12200113,1831763,2006,2017-09-30 08:25:45,2017-09-30 08:59:12,3058,Lewis Ave & Kosciuszko St,40.6924,-73.9371,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,31549,Subscriber,1992,1
12204381,1836031,1030,2017-09-30 10:13:45,2017-09-30 10:30:55,3418,Plaza St West & Flatbush Ave,40.675,-73.9711,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,28498,Subscriber,1955,1
12209871,1841521,1038,2017-09-30 11:45:03,2017-09-30 12:02:22,3310,14 St & 7 Ave,40.6638,-73.984,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,16860,Subscriber,1970,2
12211295,1842945,1115,2017-09-30 12:07:31,2017-09-30 12:26:06,3300,Prospect Park West & 8 St,40.6651,-73.9764,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,31228,Subscriber,1983,2
12211296,1842946,1116,2017-09-30 12:07:32,2017-09-30 12:26:08,3300,Prospect Park West & 8 St,40.6651,-73.9764,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,28723,Subscriber,1982,1
12213110,1844760,816,2017-09-30 12:35:22,2017-09-30 12:48:59,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,18074,Subscriber,1986,1
12213164,1844814,781,2017-09-30 12:36:08,2017-09-30 12:49:10,3324,3 Ave & 14 St,40.6685,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,19053,Subscriber,1985,2
12215733,1847383,1960,2017-09-30 13:13:28,2017-09-30 13:46:08,3486,Schermerhorn St & Bond St,40.6884,-73.9845,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,20957,Subscriber,1982,1
12222211,1853861,2938,2017-09-30 14:46:18,2017-09-30 15:35:17,365,Fulton St & Grand Ave,40.6822,-73.9615,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,15790,Customer,NaN,0
12223458,1855108,1669,2017-09-30 15:04:06,2017-09-30 15:31:55,3401,2 Ave & 9 St,40.6725,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,31026,Subscriber,1964,1
12224460,1856110,5885,2017-09-30 15:16:58,2017-09-30 16:55:04,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,25496,Customer,NaN,0
12224462,1856112,5853,2017-09-30 15:17:02,2017-09-30 16:54:36,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,28723,Customer,NaN,0
12230095,1861745,1325,2017-09-30 16:38:52,2017-09-30 17:00:57,3415,Prospect Pl & 6 Ave,40.6793,-73.9752,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,30454,Subscriber,1981,2
12232354,1864004,2467,2017-09-30 17:13:53,2017-09-30 17:55:00,262,Washington Park,40.6918,-73.9737,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,15009,Subscriber,1993,1
12233364,1865014,1331,2017-09-30 17:29:16,2017-09-30 17:51:27,3417,Baltic St & 5 Ave,40.6796,-73.9785,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,20957,Subscriber,1958,1
12238183,1869833,873,2017-09-30 18:51:57,2017-09-30 19:06:31,3373,3 St & 3 Ave,40.6751,-73.9878,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,27484,Subscriber,1985,1
12241068,1872718,563,2017-09-30 19:59:59,2017-09-30 20:09:23,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,31228,Subscriber,1988,1
12244617,1876267,793,2017-09-30 22:14:25,2017-09-30 22:27:38,3401,2 Ave & 9 St,40.6725,-73.9933,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,30733,Subscriber,1969,0
12245624,1877274,1129,2017-09-30 23:07:41,2017-09-30 23:26:31,3398,Smith St & 9 St,40.6747,-73.9979,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,20058,Subscriber,1976,1
12245625,1877275,1130,2017-09-30 23:07:42,2017-09-30 23:26:33,3398,Smith St & 9 St,40.6747,-73.9979,3478,2 Ave & 36 St - Citi Bike HQ at Industry City,40.6571,-74.0087,15211,Subscriber,1979,2

In [10]:
def dt2hrs(dt):
    time = dt.split()[1]
    if int(time[3:5]) < 30:
        return int(time[:2])
    else:
        return int(time[:2]) + .5

In [11]:
%%time
df['starthour'] = df['starttime'].map(lambda x: dt2hrs(x))

CPU times: user 19.5 s, sys: 465 ms, total: 19.9 s
Wall time: 20 s

In [12]:
%%time
# format="%Y-%m-%d" makes the process at least 10 times faster
df['starttime'] = pd.to_datetime(df['starttime'], format="%Y-%m-%d")
df['stoptime'] = pd.to_datetime(df['stoptime'], format="%Y-%m-%d")

CPU times: user 11.6 s, sys: 1.97 s, total: 13.6 s
Wall time: 13.9 s

In [13]:
%%time
df = df.sort_values('starttime').reset_index()
df.drop(['index'], 1, inplace=True)

CPU times: user 9.28 s, sys: 11.9 s, total: 21.2 s
Wall time: 24.5 s

In [14]:
df.isnull().sum()

level_0                          0
tripduration                     0
starttime                        0
stoptime                         0
start station id                 0
start station name               0
start station latitude           0
start station longitude          0
end station id                   0
end station name                 0
end station latitude             0
end station longitude            0
bikeid                           0
usertype                     16026
birth year                 1649950
gender                           0
starthour                        0
dtype: int64

In [71]:
# imputing missing values

df.loc[(df['usertype'].isnull()) & (df['birth year'].notnull()), 'usertype'] = 'Subscriber'
df.loc[(df['usertype'].isnull()) & (df['birth year'].isnull()), 'usertype'] = 'Customer'
df.loc[df['birth year'].isnull(), 'birth year'] = -1

In [72]:
%%time
int_cols = ['tripduration', 'start station id', 'end station id', 'bikeid', 'birth year', 'gender']

float_cols = ['start station latitude', 'start station longitude', 
              'end station latitude', 'end station longitude']

for c in int_cols:
    df[c] = df[c].astype(int)

for c in float_cols:
    df[c] = df[c].astype(float)

CPU times: user 23.9 s, sys: 8.49 s, total: 32.4 s
Wall time: 32.8 s

In [76]:
%%time
a = list(set(df['start station id']))
a = set([int(i) for i in a])
b = list(set(df['end station id']))
b = set([int(i) for i in b])
print(len(a), len(b), len(a.union(b)))

864 869 869
CPU times: user 3.27 s, sys: 156 ms, total: 3.43 s
Wall time: 3.43 s

In [18]:
# station id: name dictionary

stations_df = df.groupby('end station id')['end station name'].first().reset_index()
stations_dict = dict(zip(stations_df['end station id'], stations_df['end station name']))

In [19]:
tmp = df.groupby(['end station id']).\
    agg({'end station latitude': 'median', 
         'end station longitude': 'median'}).reset_index()

stations_latlng = dict()
for i in range(len(tmp)):
    stations_latlng[tmp.loc[i, 'end station id']] = (tmp.loc[i, 'end station latitude'], 
                                                     tmp.loc[i, 'end station longitude'])

In [20]:
# dictionary
pickle.dump(stations_dict, open('stations_dict.p', 'wb'))
pickle.dump(stations_latlng, open('stations_latlng.p', 'wb'))

In [21]:

# stations_dict = pickle.load(open('stations_dict.p', "rb"))

In [22]:
df.dtypes

level_0                             int64
tripduration                        int64
starttime                  datetime64[ns]
stoptime                   datetime64[ns]
start station id                    int64
start station name                 object
start station latitude            float64
start station longitude           float64
end station id                      int64
end station name                   object
end station latitude              float64
end station longitude             float64
bikeid                              int64
usertype                           object
birth year                          int64
gender                              int64
starthour                         float64
dtype: object

## Save df to feather

In [23]:
%%time
df.drop('level_0', 1, inplace=True)
df.drop(['start station name', 'end station name'], 1, inplace=True)
df.drop(['start station latitude', 'start station longitude', 
         'end station latitude', 'end station longitude'], 1, inplace=True)
df.to_feather('2017_all', index=false)

CPU times: user 4.25 s, sys: 4.74 s, total: 8.99 s
Wall time: 10.8 s

## Add temperature/raining for each date in 2017

[Temperature Data Source](https://www.wunderground.com/history/airport/KNYC/2017/1/1/CustomHistory.html?dayend=31&monthend=12&yearend=2017&req_city=&req_state=&req_statename=&reqdb.zip=&reqdb.magic=&reqdb.wmo=)

In [7]:
import datetime

In [46]:
temp_2017_all = pd.read_csv('nyc_temp_2017_all.csv',)
temp_2017_all['Events'].fillna('None', inplace=True)
temp_2017_all.head()

   2017  Temp_high  Temp_avg  Temp_low Precip Events
0     1         46        44        41      0   None
1     2         39        38        37    0.2   Rain
2     3         43        41        39   0.59   Rain
3     4         52        44        34      0   None
4     5         33        30        27      0   None

In [50]:
# replace Trace with a small number
temp_2017_all.loc[temp_2017_all['Precip'].str.contains('T'), 'Events'] = 'None'
temp_2017_all.replace('T', 0.001, inplace=True)
temp_2017_all['Precip'] = temp_2017_all['Precip'].astype(float)

temp_2017_all['Rain'] = 0
temp_2017_all.loc[temp_2017_all['Events'].str.contains('Rain'), 'Rain'] = 1

temp_2017_all['Snow'] = 0
temp_2017_all.loc[temp_2017_all['Events'].str.contains('Snow'), 'Snow'] = 1

temp_2017_all['Fog'] = 0
temp_2017_all.loc[temp_2017_all['Events'].str.contains('Fog'), 'Fog'] = 1

temp_2017_all.drop(['Events'], 1, inplace=True)

# proper dates
temp_2017_all['2017'] = np.arange(datetime.date(2017, 1, 1), datetime.date(2018, 1, 1))

In [51]:
temp_2017_all.sample(5)

          2017  Temp_high  Temp_avg  Temp_low  Precip  Rain  Snow  Fog
246 2017-09-04         80        71        61   0.000     0     0    0
243 2017-09-01         71        63        55   0.000     0     0    0
197 2017-07-17         85        79        73   0.000     0     0    0
40  2017-02-10         32        26        19   0.001     0     0    0
15  2017-01-16         43        37        30   0.000     0     0    0

In [52]:
temp_2017_all.to_csv('nyc_temp_2017.csv', index=False)